### ISSUE TITLE
Error: JS needed for stories does not loaded properly, retrying...

### ISSUE THREAD

**Issue by brennick** [gippy/instagram-scraper#102]
Getting the following error when trying to scrape stories using cookies of a logged in user

`Error: JS needed for stories does not loaded properly, retrying...`

2020-10-30T22:52:56.036Z ERROR PuppeteerCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue
2020-10-30T22:52:56.038Z   Error: JS needed for stories does not loaded properly, retrying...
2020-10-30T22:52:56.040Z       at PuppeteerCrawler.handlePageFunction (/home/myuser/src/index.js:306:44)
2020-10-30T22:52:56.042Z       at async /home/myuser/node_modules/apify/build/utils.js:362:26

**Comment by pocesar** [comment]
should work on `beta` (on master branch)
