### ISSUE TITLE
Unable to retrieve post detail

### ISSUE THREAD

**Issue by genz10** [gippy/instagram-scraper#111]
Hello,

I'm unable to retrieve post detail by providing direct URL, using cookie and residential proxy running at Apify platform, here's a snippet log for it:

```
2020-12-13T08:54:30.381Z ACTOR: Creating Docker container.
2020-12-13T08:54:30.672Z ACTOR: Starting Docker container.

2020-12-13T08:54:32.267Z INFO  System info {"apifyVersion":"0.21.8","apifyClientVersion":"0.6.0","osType":"Linux","nodeVersion":"v12.18.4"}
2020-12-13T08:54:32.432Z WARN  Cookies were used, setting maxConcurrency to Infinity. Count of available cookies: 1!
2020-12-13T08:54:32.433Z WARN  Search is disabled when Direct URLs are used
2020-12-13T08:54:32.433Z INFO  Parsed start URLs:
2020-12-13T08:54:32.435Z [
2020-12-13T08:54:32.435Z   {
2020-12-13T08:54:32.436Z     url: 'https://www.instagram.com/p/BwrsO1Bho2N/',
2020-12-13T08:54:32.436Z     userData: { pageType: 'post' }
2020-12-13T08:54:32.436Z   }
2020-12-13T08:54:32.436Z ]
2020-12-13T08:54:32.621Z INFO  PuppeteerCrawler:AutoscaledPool: state {"currentConcurrency":0,"desiredConcurrency":2,"systemStatus":{"isSystemIdle":true,"memInfo":{"isOverloaded":false,"limitRatio":0.2,"actualRatio":null},"eventLoopInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":null},"cpuInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":null},"clientInfo":{"isOverloaded":false,"limitRatio":0.3,"actualRatio":null}}}
2020-12-13T08:54:34.257Z INFO  Launching Puppeteer {"stealth":true,"useChrome":true,"ignoreHTTPSErrors":true,"args":["--enable-features=NetworkService","--ignore-certificate-errors","--no-sandbox","--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"],"timeout":15000,"headless":true,"executablePath":"/usr/bin/google-chrome","defaultViewport":
2020-12-13T08:54:37.613Z ERROR PuppeteerCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.instagram.com/p/BwrsO1Bho2N/","retryCount":1,"id":"YCyUc93vUGzK9eA"}
2020-12-13T08:54:37.614Z   TypeError: Cannot read property 'shortcode_media' of undefined
2020-12-13T08:54:37.614Z       at getItemSpec (/home/myuser/src/helpers.js:59:56)
2020-12-13T08:54:37.614Z       at PuppeteerCrawler.handlePageFunction (/home/myuser/src/index.js:277:26)
2020-12-13T08:54:37.615Z       at runMicrotasks (<anonymous>)
2020-12-13T08:54:37.615Z       at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-12-13T08:54:37.616Z       at async /home/myuser/node_modules/apify/build/utils.js:362:26
```

Wondering if I did something wrong?

Thanks

**Comment by pocesar** [comment]
can you post the rest of your INPUT?

**Comment by genz10** [comment]
Here it is:
```
{
  "search": "Nature",
  "searchType": "user",
  "directUrls": [
    "https://www.instagram.com/p/BwrsO1Bho2N/"
  ],
  "resultsType": "details",
  "proxy": {
    "useApifyProxy": false,
    "proxyUrls": [
      WORKING_PROXY
    ]
  },
  "loginCookies": [
   COOKIES_ARRAY
  ],
  "expandOwners": false,
  "includeHasStories": false,
  "extendOutputFunction": "($) => { return {} }",
  "searchLimit": 10,
  "resultsLimit": 200,
  "maxRequestRetries": 5,
  "scrollWaitSecs": 15,
  "maxErrorCount": 3,
  "cookiesPerConcurrency": 0,
  "likedByLimit": 0,
  "followingLimit": 0,
  "followedByLimit": 0
}
```

**Comment by genz10** [comment]
Anyway @pocesar , wondering if there's any documentation to running it locally? for debugging purpose, I was trying to run it on my local but got no luck..

**Comment by pocesar** [comment]
this is fixed in `beta` on the platform (here on `master`)
