### ISSUE TITLE
ERROR TimeoutError: waiting for function failed: timeout 15000ms exceeded

### ISSUE THREAD

**Issue by vanishinggradient** [gippy/instagram-scraper#127]
[logs](https://api.apify.com/v2/logs/qcPun7g20IRiXIyBJ)

`
2021-04-14T05:02:08.188Z INFO  Opening page type: user on https://www.instagram.com/neetijoshi2410
2021-04-14T05:02:28.487Z ERROR TimeoutError: waiting for function failed: timeout 15000ms exceeded
2021-04-14T05:02:28.632Z ERROR PuppeteerCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.instagram.com/neetijoshi2410","retryCount":1,"id":"Y4EA53BujjeAdmy"}
2021-04-14T05:02:28.642Z   Error: Page didn't load properly with login, retrying...
2021-04-14T05:02:28.645Z       at PuppeteerCrawler.handlePageFunction (/home/myuser/src/main.js:363:23)
2021-04-14T05:02:28.647Z       at async PuppeteerCrawler._handleRequestFunction (/home/myuser/node_modules/apify/build/crawlers/browser_crawler.js:324:13)
2021-04-14T05:02:28.649Z       at async PuppeteerCrawler._runTaskFunction (/home/myuser/node_modules/apify/build/crawlers/basic_crawler.js:423:13)
2021-04-14T05:02:28.651Z       at async AutoscaledPool._maybeRunTask (/home/myuser/node_modules/apify/build/autoscaling/autoscaled_pool.js:388:13)
`

posting input after removing LoginCookies

[input.txt](https://github.com/gippy/instagram-scraper/files/6308292/input.txt)

**Comment by pocesar** [comment]
this is expected and will be retried, no need to worry about those transient errors
