### ISSUE TITLE
PuppeteerCrawler: handleRequestFunction failed

### ISSUE THREAD

**Issue by Jarvis3310** [gippy/instagram-scraper#128]
what happen?

2021-04-14T10:31:46.964Z INFO  Opening page type: post on https://www.instagram.com/p/CNC6Ijfh828/
2021-04-14T10:31:47.072Z ERROR PuppeteerCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.instagram.com/p/CNC6Ijfh828/","retryCount":1,"id":"ghhYcwkO3AS3CpW"}
2021-04-14T10:31:47.075Z   Error: net::ERR_SSL_PROTOCOL_ERROR at https://www.instagram.com/p/CNC6Ijfh828/
2021-04-14T10:31:47.076Z       at navigate (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:115:23)
2021-04-14T10:31:47.078Z       at processTicksAndRejections (internal/process/task_queues.js:93:5)
2021-04-14T10:31:47.080Z       at async FrameManager.navigateFrame (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:90:21)
2021-04-14T10:31:47.082Z       at async Frame.goto (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:416:16)
2021-04-14T10:31:47.084Z       at async Page.goto (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:789:16)
2021-04-14T10:31:47.086Z       at async PuppeteerCrawler._handleNavigation (/home/myuser/node_modules/apify/build/crawlers/browser_crawler.js:359:40)
2021-04-14T10:31:47.088Z       at async PuppeteerCrawler._handleRequestFunction (/home/myuser/node_modules/apify/build/crawlers/browser_crawler.js:314:13)
2021-04-14T10:31:47.090Z       at async PuppeteerCrawler._runTaskFunction (/home/myuser/node_modules/apify/build/crawlers/basic_crawler.js:421:13)
2021-04-14T10:31:47.092Z       at async AutoscaledPool._maybeRunTask (/home/myuser/node_modules/apify/build/autoscaling/autoscaled_pool.js:388:13)

**Comment by pocesar** [comment]
either you don't have access to proxies or it's misconfigured
