### ISSUE TITLE
Array of login cookies: getting a challenge page does not let us consuming the other cookies

### ISSUE THREAD

**Issue by Jeanquetil** [gippy/instagram-scraper#130]
Hello,

We are passing an array of login cookies to scrap Instagram stories but it seems to consume the first login cookie only. Everytime, after ~90 successful scraping calls, we are getting a challenge page (phone verification, face/video check, etc.) which leads to a `This instagram page is not supported.` error message on Apify.
This is happening after the login process which seems considered as successful.

In this case, can we handle this error to mark the session as bad so that we could consume the other login cookies?

Thanks a lot

Apify log example:
```
2021-06-08T01:51:05.486Z ACTOR: Pulling Docker image from repository.
2021-06-08T01:51:05.556Z ACTOR: Creating Docker container.
2021-06-08T01:51:05.690Z ACTOR: Starting Docker container.
2021-06-08T01:51:08.154Z INFO  System info {"apifyVersion":"1.1.2","apifyClientVersion":"1.1.0","osType":"Linux","nodeVersion":"v14.16.1"}
2021-06-08T01:51:08.434Z WARN  Cookies were used, setting maxConcurrency to 0. Count of available cookies: 5!
2021-06-08T01:51:09.748Z WARN  Search is disabled when Direct URLs are used
2021-06-08T01:51:09.751Z INFO  Parsed start URLs:
2021-06-08T01:51:09.753Z [
2021-06-08T01:51:09.756Z   {
2021-06-08T01:51:09.758Z     url: 'https://www.instagram.com/stories/lifestyle.sarita',
2021-06-08T01:51:09.760Z     userData: { pageType: 'story' }
2021-06-08T01:51:09.763Z   }
2021-06-08T01:51:09.766Z ]
2021-06-08T01:51:10.084Z INFO  PuppeteerCrawler:AutoscaledPool: state {"currentConcurrency":0,"desiredConcurrency":1,"systemStatus":{"isSystemIdle":true,"memInfo":{"isOverloaded":false,"limitRatio":0.2,"actualRatio":null},"eventLoopInfo":{"isOverloaded":false,"limitRatio":0.6,"actualRatio":null},"cpuInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":null},"clientInfo":{"isOverloaded":false,"limitRatio":0.3,"actualRatio":null}}}
2021-06-08T01:51:12.359Z INFO  Opening page type: story on https://www.instagram.com/stories/lifestyle.sarita
2021-06-08T01:51:22.411Z INFO  unsupported page {"Challenge":[{"challengeType":"AcknowledgeForm","errors":[],"experiments":{},"extraData":{"__typename":"GraphChallengePage","content":"[array]"},"fields":{},"navigation":{"forward":"/challenge/","replay":"/challenge/replay/"},"privacyPolicyUrl":"/about/legal/privacy/","type":"CHALLENGE","challenge_context":"{\"step_name\": \"\", \"is_stateless\": false}"}]}
2021-06-08T01:51:22.414Z ERROR PuppeteerCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.instagram.com/stories/lifestyle.sarita","retryCount":1,"id":"BdUZWIQd4SVeqBb"}
2021-06-08T01:51:22.417Z   Error: This instagram page is not supported.
2021-06-08T01:51:22.419Z       at Object.unsupportedPage (/home/myuser/src/errors.js:5:28)
2021-06-08T01:51:22.422Z       at getItemSpec (/home/myuser/src/helpers.js:104:18)
2021-06-08T01:51:22.424Z       at PuppeteerCrawler.handlePageFunction (/home/myuser/src/main.js:373:26)
2021-06-08T01:51:22.426Z       at processTicksAndRejections (internal/process/task_queues.js:93:5)
2021-06-08T01:51:22.428Z       at async PuppeteerCrawler._handleRequestFunction (/home/myuser/node_modules/apify/build/crawlers/browser_crawler.js:324:13)
2021-06-08T01:51:22.431Z       at async PuppeteerCrawler._runTaskFunction (/home/myuser/node_modules/apify/build/crawlers/basic_crawler.js:423:13)
2021-06-08T01:51:22.434Z       at async AutoscaledPool._maybeRunTask (/home/myuser/node_modules/apify/build/autoscaling/autoscaled_pool.js:388:13)
2021-06-08T01:51:26.456Z INFO  Opening page type: story on https://www.instagram.com/stories/lifestyle.sarita
2021-06-08T01:51:30.100Z INFO  unsupported page {"Challenge":[{"challengeType":"AcknowledgeForm","errors":[],"experiments":{},"extraData":{"__typename":"GraphChallengePage","content":"[array]"},"fields":{},"navigation":{"forward":"/challenge/","replay":"/challenge/replay/"},"privacyPolicyUrl":"/about/legal/privacy/","type":"CHALLENGE","challenge_context":"{\"step_name\": \"\", \"is_stateless\": false}"}]}
2021-06-08T01:51:30.103Z ERROR PuppeteerCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.instagram.com/stories/lifestyle.sarita","retryCount":2,"id":"BdUZWIQd4SVeqBb"}
2021-06-08T01:51:30.105Z   Error: This instagram page is not supported.
2021-06-08T01:51:30.108Z       at Object.unsupportedPage (/home/myuser/src/errors.js:5:28)
2021-06-08T01:51:30.110Z       at getItemSpec (/home/myuser/src/helpers.js:104:18)
2021-06-08T01:51:30.113Z       at PuppeteerCrawler.handlePageFunction (/home/myuser/src/main.js:373:26)
2021-06-08T01:51:30.115Z       at processTicksAndRejections (internal/process/task_queues.js:93:5)
2021-06-08T01:51:30.117Z       at async PuppeteerCrawler._handleRequestFunction (/home/myuser/node_modules/apify/build/crawlers/browser_crawler.js:324:13)
2021-06-08T01:51:30.127Z       at async PuppeteerCrawler._runTaskFunction (/home/myuser/node_modules/apify/build/crawlers/basic_crawler.js:423:13)
2021-06-08T01:51:30.129Z       at async AutoscaledPool._maybeRunTask (/home/myuser/node_modules/apify/build/autoscaling/autoscaled_pool.js:388:13)
2021-06-08T01:51:33.912Z INFO  Opening page type: story on https://www.instagram.com/stories/lifestyle.sarita
2021-06-08T01:51:36.386Z INFO  unsupported page {"Challenge":[{"challengeType":"AcknowledgeForm","errors":[],"experiments":{},"extraData":{"__typename":"GraphChallengePage","content":"[array]"},"fields":{},"navigation":{"forward":"/challenge/","replay":"/challenge/replay/"},"privacyPolicyUrl":"/about/legal/privacy/","type":"CHALLENGE","challenge_context":"{\"step_name\": \"\", \"is_stateless\": false}"}]}
2021-06-08T01:51:36.456Z ERROR https://www.instagram.com/stories/lifestyle.sarita: Request https://www.instagram.com/stories/lifestyle.sarita failed 3 times, not retrying any more
2021-06-08T01:51:36.639Z INFO  PuppeteerCrawler: All the requests from request list and/or request queue have been processed, the crawler will shut down.
2021-06-08T01:51:36.786Z INFO  PuppeteerCrawler: Final request statistics: {"requestsFinished":0,"requestsFailed":1,"retryHistogram":[null,null,1],"requestAvgFailedDurationMillis":2866,"requestAvgFinishedDurationMillis":null,"requestsFinishedPerMinute":0,"requestsFailedPerMinute":2,"requestTotalDurationMillis":2866,"requestsTotal":1,"crawlerRuntimeMillis":26779}
```

**Comment by ThomasSertorio** [comment]
This is a problem for us too 😬.

We were expecting to decrease the rate of blocking using an array of cookies but we can't figure out to get it working.

**Comment by pocesar** [comment]
released as beta on the platform
