### ISSUE TITLE
Failure to load comments

### ISSUE THREAD

**Issue by apienx** [gippy/instagram-scraper#43]
Comments feature appears to be broken. Snippet of the log below.

```
2020-05-05T17:37:33.460Z   Error: Comments can only be loaded from posts detail page.
2020-05-05T17:37:33.461Z       at Object.notPostPage (/home/myuser/src/errors.js:12:24)
2020-05-05T17:37:33.462Z       at scrapeComments (/home/myuser/src/comments.js:110:61)
2020-05-05T17:37:33.463Z       at PuppeteerCrawler.handlePageFunction (/home/myuser/src/index.js:135:52)
2020-05-05T17:37:33.464Z       at runMicrotasks (<anonymous>)
2020-05-05T17:37:33.464Z       at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-05-05T17:37:33.467Z       at async /home/myuser/node_modules/apify/build/utils.js:317:26
2020-05-05T17:37:33.471Z ERROR Error: Protocol error (Network.getResponseBody): Session closed. Most likely the page has been closed.
```

**Comment by metalwarrior665** [comment]
What is your INPUT? The error message is pretty clear here 
``` Comments can only be loaded from posts detail page.```

**Comment by metalwarrior665** [comment]
Basically, we need to rework the INPUT SCHEMA completely to make this all more intuitive. This depends on INPUT SCHEMA v2 which is not coming very soon. I hope we could make some changes this year at least.

**Comment by metalwarrior665** [comment]
Duplicate of https://github.com/gippy/instagram-scraper/issues/52
