### ISSUE TITLE
Missing instructions

### ISSUE THREAD

**Issue by marcelcaferati** [gippy/instagram-scraper#7]
By any chance is there a way you can add instructions on how to run this solution localy?

**Comment by byamir** [comment]
Please add this thank you. I'm having an issue where it gives me :
```
Run: npm start
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module 'apify'
Require stack:
- /Users/amirali/Desktop/instagram-scraper/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/amirali/Desktop/instagram-scraper/main.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/amirali/Desktop/instagram-scraper/main.js' ]
}
Error: npm exited with code 1
```

**Comment by byamir** [comment]
Fixed it by typing `npm install`. This is exactly why we need some documentation. I'm getting a new error 
```
Run: npm start
INFO  System info {"apifyVersion":"0.20.4","apifyClientVersion":"0.6.0","osType":"Darwin","nodeVersion":"v12.16.2"}
DEBUG Events: Environment variable APIFY_ACTOR_EVENTS_WS_URL is not set, no events from Apify platform will be emitted.
ERROR The function passed to Apify.main() threw an exception:
  TypeError: Cannot read property 'apifyProxyGroups' of undefined
      at main (/Users/amirali/Desktop/instagram-scraper/src/index.js:30:15)
      at async run (/Users/amirali/Desktop/instagram-scraper/node_modules/apify/build/actor.js:195:13)
Error: npm exited with code 91
```

**Comment by metalwarrior665** [comment]
Yes, you are right, we were doing a lot of important updates lately so will add this instruction once that is done. Also keep in mind that the scraper is tailored for running at Apify cloud. Right now, it is not possible to run without proxies (Apify or custom proxies) but we should lift this restriction for local runs.
