### ISSUE TITLE
Search is blocked on current proxy IP

### ISSUE THREAD

**Issue by ladderapplication** [gippy/instagram-scraper#75]
Hi, I have regularly been able to use this scraper for specific tasks, but it now fails even by running the default limited "Nature" search. Please see the run below.

2020-07-08T18:47:56.757Z ACTOR: Creating Docker container.
2020-07-08T18:47:57.184Z ACTOR: Starting Docker container.
2020-07-08T18:47:58.865Z INFO  System info {"apifyVersion":"0.20.4","apifyClientVersion":"0.6.0","osType":"Linux","nodeVersion":"v12.18.0"}
2020-07-08T18:47:58.867Z WARN  You are using an outdated version (0.20.4) of Apify SDK. We recommend you to update to the latest version (0.21.0).
2020-07-08T18:47:58.867Z          Read more about Apify SDK versioning at: https://help.apify.com/en/articles/3184510-updates-and-versioning-of-apify-sdk
2020-07-08T18:47:59.042Z WARN  You are using Apify proxy but not residential group! It is very likely it will not work properly. Please contact support@apify.com for access to residential proxy.
2020-07-08T18:47:59.045Z INFO  Searching for "Nature"
2020-07-08T18:48:00.109Z WARN  Server returned non-json answer, retrying one more time
2020-07-08T18:48:00.110Z INFO  Searching for "Nature"
2020-07-08T18:48:00.902Z ERROR The function passed to Apify.main() threw an exception:
2020-07-08T18:48:00.903Z   Error: Search is blocked on current proxy IP
2020-07-08T18:48:00.904Z       at searchUrls (/home/myuser/src/search.js:53:15)
2020-07-08T18:48:00.905Z       at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-07-08T18:48:00.906Z       at async main (/home/myuser/src/index.js:76:16)
2020-07-08T18:48:00.907Z       at async run (/home/myuser/node_modules/apify/build/actor.js:195:13)

**Comment by pocesar** [comment]
thanks for the report, this is being worked and a new version should be available soon

**Comment by metalwarrior665** [comment]
Check this line of the log:

```WARN You are using Apify proxy but not residential group! It is very likely it will not work properly. Please contact support@apify.com for access to residential proxy.```

@pocesar is working on a version that will work without residential but it might not work 100%
